package main

import (
	"fmt"
	"go/types"
	"log"
	"reflect"
	"strings"

	"github.com/dave/jennifer/jen"
	"golang.org/x/tools/go/packages"
	"gorm.io/gorm/schema"
)

type FieldInfo struct {
	FieldName  string
	ColumnName string
}

type Generator struct {
	pkgName    string
	data       map[string][]FieldInfo // TypeName -> Fields
	outputPath string
	modulePath string
}

func (g *Generator) processTypes(pkg *packages.Package) {
	typesList := strings.Split(*typeNames, ",")
	for _, typeName := range typesList {
		obj := pkg.Types.Scope().Lookup(typeName)
		if obj == nil {
			log.Printf("警告: 在包 %s 中未找到类型 %s", pkg.Name, typeName)
			continue
		}

		if _, ok := obj.(*types.TypeName); !ok {
			log.Printf("警告: %s 不是一个类型", typeName)
			continue
		}

		structType, ok := obj.Type().Underlying().(*types.Struct)
		if !ok {
			log.Printf("警告: %s 不是一个结构体", typeName)
			continue
		}

		g.data[typeName] = g.extractFields(structType)
	}
}

func (g *Generator) extractFields(st *types.Struct) []FieldInfo {
	// 收集所有直接定义的字段，用于处理 Shadowing
	directFields := make(map[string]struct{})
	for i := 0; i < st.NumFields(); i++ {
		field := st.Field(i)
		if !field.Anonymous() && field.Exported() {
			directFields[field.Name()] = struct{}{}
		}
	}

	var fields []FieldInfo
	// 用于记录已收集的字段名，防止重复（如同级嵌入冲突或被覆盖）
	seenFields := make(map[string]struct{})

	for i := 0; i < st.NumFields(); i++ {
		field := st.Field(i)
		tag := st.Tag(i)

		// 处理嵌入字段
		if field.Anonymous() {
			// 获取嵌入字段的类型
			embeddedType := field.Type()
			if ptr, ok := embeddedType.(*types.Pointer); ok {
				embeddedType = ptr.Elem()
			}

			if embeddedStruct, ok := embeddedType.Underlying().(*types.Struct); ok {
				// 递归提取嵌入字段的字段
				subFields := g.extractFields(embeddedStruct)
				for _, subField := range subFields {
					// 只有当该字段没有被当前结构体直接覆盖，且未被处理过时，才添加
					if _, direct := directFields[subField.FieldName]; !direct {
						if _, seen := seenFields[subField.FieldName]; !seen {
							fields = append(fields, subField)
							seenFields[subField.FieldName] = struct{}{}
						}
					}
				}
			}
			continue
		}

		// 如果字段未导出，跳过
		if !field.Exported() {
			continue
		}

		fieldName := field.Name()

		// 如果已经处理过（理应已经在 directFields 中），跳过？
		// 由于遍历顺序，直接字段肯定会在循环中遇到。
		// 我们在处理嵌入字段时已经避开了 directFields。
		// 这里再次检查 seenFields 主要是为了逻辑的严谨性，其实对于直接字段，这里是第一次添加。
		if _, seen := seenFields[fieldName]; seen {
			continue
		}

		columnName := namingStrategy.ColumnName("", fieldName)

		if tag != "" {
			structTag := reflect.StructTag(strings.Trim(tag, "`"))
			if gormTag := structTag.Get("gorm"); gormTag != "" {
				settings := schema.ParseTagSetting(gormTag, ";")
				if col, ok := settings["COLUMN"]; ok {
					columnName = col
				}
			}
		}

		fields = append(fields, FieldInfo{
			FieldName:  fieldName,
			ColumnName: columnName,
		})
		seenFields[fieldName] = struct{}{}
	}
	return fields
}

func (g *Generator) generate() {
	if len(g.data) == 0 {
		return
	}

	f := jen.NewFile(g.pkgName)
	f.HeaderComment("Code generated by gen-props. DO NOT EDIT.")

	// 使用 g.modulePath 构造 query 包的导入路径
	queryPkg := g.modulePath + "/pkg/query"

	for typeName, fields := range g.data {
		f.Comment(fmt.Sprintf("%sProps defines the fields for %s", typeName, typeName))

		// 构建结构体字段
		structFields := []jen.Code{}
		for _, field := range fields {
			structFields = append(structFields, jen.Id(field.FieldName).Qual(queryPkg, "Column"))
		}

		f.Var().Id(typeName + "Props").Op("=").Struct(structFields...).Op("{").Do(func(s *jen.Statement) {
			for _, field := range fields {
				s.Line().Id(field.FieldName).Op(":").Lit(field.ColumnName).Op(",")
			}
			s.Line()
		}).Op("}")
	}

	err := f.Save(g.outputPath)
	if err != nil {
		log.Fatalf("writing output: %s", err)
	}
	log.Printf("generated %s", g.outputPath)
}
