// Code generated by gen-props. DO NOT EDIT.
package model

import "gorm-query-template/pkg/query"

// UserProps defines the fields for User
var UserProps = struct {
	ID        query.Column
	CreatedAt query.Column
	UpdatedAt query.Column
	DeletedAt query.Column
	UserName  query.Column
	Email     query.Column
	Age       query.Column
	Status    query.Column
}{
	ID:        "id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
	UserName:  "user_name",
	Email:     "email",
	Age:       "age",
	Status:    "status",
}
